### ISSUE TITLE
update to work on Rust stable

### ISSUE THREAD

**Issue by BurntSushi** [dguo/strsim-rs#1]
Are there any plans to get this crate working on Rust stable? It'd be great to use your implementation of Levenshtein in Docopt. :-) https://github.com/docopt/docopt.rs/pull/120

**Comment by dguo** [comment]
Done! As of version 0.3.0, it will compile cleanly on both nightly and beta. See https://travis-ci.org/dguo/strsim-rs/jobs/60644557

**Comment by BurntSushi** [comment]
@dguo Thanks! All set. :D
