### ISSUE TITLE
add Pass-Join for large lists of strings

### ISSUE THREAD

**Issue by thadguidry** [dguo/strsim-rs#11]
I'd like to see other algorithms added that help support Big Data scenarios and large lists of strings that typically are handled ungracefully with Map Reduce or other ill-suited methods for string comparison.

One of those algorithms that I would like to see added would be Pass-Join.

- http://dbgroup.cs.tsinghua.edu.cn/ligl/papers/fcs15-string-survey.pdf
- http://dbgroup.cs.tsinghua.edu.cn/ligl/papers/tods13-passjoin.pdf
- https://github.com/squidfunk/pass-join

**Comment by dguo** [comment]
Thanks for the suggestion. Pass-Join seems fairly involved, so I'm reluctant to dig in right now since just understanding what it entails seems like it will take some time. Any chance you have a more digestible source? I did a quick Google search but couldn't find much else on it.

**Comment by dguo** [comment]
I did submit an issue to that repo last year asking for more info, but the author said it was only a prototype and that he didn't have time to finish it. And now it looks like the repo has been deleted or made private.

I'm going to close this issue for now, but feel free to let me know if it a full, open source implementation can be found.

**Comment by thadguidry** [comment]
@dguo Sure, understandable.

**Comment by Yomguithereal** [comment]
Hello everyone. Not sure if this is of any interest of you but I have a python implementation of the algo right here in one of my undocumented, unfortunately, library: https://github.com/Yomguithereal/fog/blob/master/fog/clustering/passjoin.py

**Comment by thadguidry** [comment]
@Yomguithereal I'd love to see that also written in Rust as well!  probably not too hard for you?

**Comment by Yomguithereal** [comment]
> @Yomguithereal I'd love to see that also written in Rust as well! probably not too hard for you if you worked with @dguo on this who knows Rust?

Unfortunately I don't know Rust so well, especially the hashmap side of things but I can indeed assist anyone willing to try the conversion. The paper is a bit obscure at times but the gist of the algorithm is not hard to grasp. One can even leverage this algorithm to create an index rather than use it for one-pass clustering. Haven't had the time to benchmark it against DAFSA indices but I have the feeling it could be faster on k <= 1 or 2.

> Oh wait, your entire FOG library is MIT licensed.

Sure, feel free to use anything from it.
