### ISSUE TITLE
please exclude "dev" and "appveyor.yml" from crates.io

### ISSUE THREAD

**Issue by ignatenkobrain** [dguo/strsim-rs#13]
Those files are unnecessary there...

**Comment by dguo** [comment]
I asked in the Cargo IRC chat about this, and based on the replies I got, excluding these kinds of files is not common practice.

I understand the argument for not including them if they aren't necessary, but then it seems like even the README, test files, etc. aren't strictly necessary either. Figuring out where to draw the line seems like more trouble than it's worth when these files are so small anyway.
