### ISSUE TITLE
Normalized Levenshtein score

### ISSUE THREAD

**Issue by gentoid** [dguo/strsim-rs#19]
Hello!

While Levenshtein calculates the minimum number of a string "mutations" there are situations where it's useful to get normalized score, where returned value is calculated as the following:

```rust
1.0 - levenshtein(a, b) / max(a, b);
```

What do you think, is it worth adding such a function here? I could add that. At the same time, it could be a practice for me in writing Rust code :blush:

**Comment by gentoid** [comment]
As for me, logical seems to be `1.0` as an exact match, because for other metrics (such as Jaro, Jaro-Winckler) `1.0` also means an exact match. So it'll be an uniformity. But let's try find papers on that

I found this paper https://hpi.de/fileadmin/user_upload/fachgebiete/naumann/folien/SS13/DPDC/DPDC_12_Similarity.pdf , where one can find the same calculations. See page 9 there

Also found this, with the same calculations https://wiki.duraspace.org/display/VIVO/NormalizedLevenshteinDifference

Here NLD also defined in the same way http://www.fon.hum.uva.nl/archive/2015/icphs/2015-icphs-PostLeussen.pdf

If to speak about algorithms in code, then I saw [Ruby's FuzzyMatch](https://github.com/seamusabshere/fuzzy_match/blob/ae3675d78ff71dd3d2af28a6f3763697e66a3dd9/lib/fuzzy_match/score/pure_ruby.rb#L81) uses the same approach, R uses the same in https://www.rdocumentation.org/packages/DescTools/versions/0.99.19/topics/StrDist

Given all that, looks like it is correct to assume that 1.0 should mean exact match

**Comment by dguo** [comment]
Okay, I'm convinced. Thanks for the in-depth research. Feel free to go for it, with 1.0 meaning exact match.

**Comment by gentoid** [comment]
Great :+1:
