### ISSUE TITLE
Incremental calculation of Levenshtein distance

### ISSUE THREAD

**Issue by vks** [dguo/strsim-rs#21]
I have some code for calculating the Levenshtein distance between a given string and a second string given character-by-character by reusing previous calculations, effectively generalizing `strsim::levenshtein`. Is this of interest for this project?

**Comment by dguo** [comment]
Hi, could you explain a little more what the intention is? I'm not sure what you mean. 

Is the goal to provide a memory-efficient method when it would be too expensive to provide the entire string at once?

**Comment by vks** [comment]
The idea is to calculate `levenshtein(a, &b[..1]), levenshtein(a, &b[..2]), levenshtein(a, &b[..3]), ..., levenshtein(a, b)` efficiently by reusing previous state. This can be achieved by refactoring the algorithm to have a struct `Levenshtein` with the following methods:

```rust
fn new(a: &str) -> Levenshtein;
fn push(&mut self, code_b: char);
fn get(&self) -> usize;
```

Then the following is equivalent to `levenshtein(a, b)`, but more flexible:
```rust
let mut l = Levenshtein::new(a);
for code_b in b.chars() {
    l.push(code_b);
}
l.get()
```

**Comment by dguo** [comment]
I see. Thanks.

Is there a practical application for this use case? I haven't seen anything like it before in other `levenshtein` libraries.

**Comment by vks** [comment]
> Is there a practical application for this use case?

A use case would be to calculate the Levenshtein distance to a given string as you type.

I was thinking of using this for correcting typos while typing, but there you actually want to find the strings out of a big set that have the shortest distance to the typed string, so I did not end up using the code.

**Comment by dguo** [comment]
Given that you didn't even use it yourself, I'd prefer to leave it out of the library for now. Thanks for the suggestion though. 

Maybe an alternative would be to store the entire set in the struct and then maintain a cost matrix for each pair of target and potential result. But this would probably use more memory, and depending on the size of the set, just recalculating from scratch with every character may be fast enough. As far as I can tell, this library isn't used anywhere that would really benefit from such an approach.

**Comment by dguo** [comment]
Closing this for now. If anyone has a real need for this feature, please leave a comment.
