### ISSUE TITLE
examples in README fail assertion

### ISSUE THREAD

**Issue by Dowwie** [dguo/strsim-rs#24]
Not sure whether this was intentional but two assertions fail in the README example.  These thresholds, however, work:
```rust
    assert!((jaro("Friedrich Nietzsche", "Jean-Paul Sartre") - 0.392).abs() < 0.00012);
    assert!((jaro_winkler("cheeseburger", "cheese fries") - 0.911).abs() < 0.00012);
```

**Comment by dguo** [comment]
Yep, that was my bad. I just fixed it. Thanks for reporting it!
