### ISSUE TITLE
please add a pinned Rust version to CI

### ISSUE THREAD

**Issue by BurntSushi** [dguo/strsim-rs#26]
The latest release of `strsim` (0.8) increased its minimum required Rust version to build. There is no problem with that, but in doing so, I'd now like to increase my minimum Rust version in my CI config to accommodate the `strsim` update. In order to do that, I need to know what Rust version `strsim` compiles with. In the ecosystem, one convention used to communicate this is to add a specific Rust version in the CI config. Here is an example: https://github.com/BurntSushi/byteorder/blob/bdcc6bf676a1ed17eae68257bfa4726a1f0ec068/.travis.yml#L4

Could you please add a pinned version to your CI config? (Note that I am not asking for any specific semver policy around the minimum Rust version supported, but rather, just a somewhat more structured means of communicating what version of Rust strsim compiles with.)

**Comment by BurntSushi** [comment]
Thanks!

**Comment by dguo** [comment]
No problem.

It didn't occur to me that Cargo doesn't have a way of specifying Rust versions in the way [npm](https://docs.npmjs.com/files/package.json#engines) does. I found this [RFC](https://github.com/rust-lang/rfcs/pull/2182) and some of your [earlier discussion](https://github.com/rust-lang-nursery/api-guidelines/issues/123#issuecomment-342470263) on the issue.
