### ISSUE TITLE
Maintaining this crate

### ISSUE THREAD

**Issue by lovasoa** [dguo/strsim-rs#33]
Hi @dguo !
  Would you mind adding me (or someone else if they volunteer) as a maintainer of this crate on github and crates.io ? 
  This crate seems to have several active users, and you do not seem to have a lot of time for it. It would be a pity if the crate died.

**Comment by dguo** [comment]
Hey, thanks for bearing with me. I had a lot of personal stuff going on this past week in particular, but going forward, I'm going to make an effort to incorporate open source maintenance into my daily routine. If it becomes an issue again, don't hesitate to ping me again.
