### ISSUE TITLE
Panic for jaro when both strings are 1 length

### ISSUE THREAD

**Issue by kdar** [dguo/strsim-rs#5]
I found this while using clap-rs, but if jaro() is called with two strings of length 1, it will panic with an overflow.

**Comment by dguo** [comment]
Fixed. Thanks for reporting it! I'll bump the patch version and submit a pull request for `clap-rs` since it looks like it's on an older minor version.

**Comment by kdar** [comment]
Awesome! Thank you for your quick response.
