### ISSUE TITLE
Performance of Damerau Levenshtein is low

### ISSUE THREAD

**Issue by nanthony007** [dguo/strsim-rs#51]
I am unsure as to the cause of this. I know the DL algorithm is significantly more complex than the OSA algorithm but some crude benchmarks show the results below when simply comparing "alcohol" and "acloholism".

I just wanted to post this to ensure the algorithm has the correct implementation given this package's **large** usage rate.

Times below are average benchmarks in nanoseconds.

<img width="630" alt="CleanShot 2022-11-28 at 09 29 52@2x" src="https://user-images.githubusercontent.com/45318637/204302983-6cf5b1c6-5bc8-4836-b3aa-bdcf4c7b5f13.png">

**Comment by maxbachmann** [comment]
https://github.com/dguo/strsim-rs/commit/9d0a95021d0c80d3a86e2b18810cdb6605809136 improves the performance significantly. E.g. for your strings I do now get the following runtimes on my machine:
```
test benches::bench_damerau_levenshtein            ... bench:         219 ns/iter (+/- 8)
test benches::bench_jaro_winkler                   ... bench:          63 ns/iter (+/- 1)
test benches::bench_levenshtein                    ... bench:          87 ns/iter (+/- 1)
test benches::bench_osa_distance                   ... bench:         136 ns/iter (+/- 3)
test benches::bench_sorensen_dice                  ... bench:         365 ns/iter (+/- 8)
```
while previously I would get:
```
test benches::bench_damerau_levenshtein            ... bench:         735 ns/iter (+/- 15)
```

**Comment by nanthony007** [comment]
This is awesome thank you! Much more in line with what I was expecting perf wise.

**Comment by maxbachmann** [comment]
Yes there will be a new release soon. Probably once we have https://github.com/dguo/strsim-rs/pull/58 merged.
