### ISSUE TITLE
Add a law-abiding version of Damerau-Levenshtein distance

### ISSUE THREAD

**Issue by lfairy** [dguo/strsim-rs#8]
There are two versions of the [Damerau-Levenshtein distance](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance#Algorithm). It looks like `strsim` only provides the first version, which is not a formal metric. It would be nice if `strsim` provides the second version as well, as this version does have the metric property.

As for why I need this: I'd like to use this library with a [BK-tree](https://en.wikipedia.org/wiki/BK-tree), which needs a metric to work.

**Comment by dguo** [comment]
Cool! I'll take a look at what implementing the second version will take once I have some more free time.

**Comment by dguo** [comment]
Sorry for the delay. The implementation should be fixed now, and the original implementation has been renamed to `osa_distance`. It's published on Crates as version [0.6.0](https://crates.io/crates/strsim/0.6.0).
