### ISSUE TITLE
Please don't include the generated docs in the repository

### ISSUE THREAD

**Issue by joshtriplett** [dguo/strsim-rs#9]
strsim includes a complete copy of the generated documentation in the repository, and thus in the crate source.  Please consider dropping that copy, in favor of letting cargo build it (`cargo doc`) or using docs.rs .

Having a generated copy of the documentation in the source makes distribution packaging more difficult, as doing so embeds various files that distributions prefer to maintain a single copy of (such as the various javascript files, css files, and fonts).

**Comment by dguo** [comment]
Good catch. I originally wanted to check it in so that it could be served by GitHub Pages. Then I discovered `docs.rs`, but I forgot to remove the directory from the repo. I'll take of it later today.

**Comment by joshtriplett** [comment]
Thanks!
